version: "3.9"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: jobsdb
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "user" ]
      interval: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
  api:
    build: ./api
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app

  worker1:
    build: ./worker1
    depends_on:
        rabbitmq:
            condition: service_healthy

    volumes:
      - ./worker1:/app
  worker2:
    build: ./worker2
    depends_on:
        rabbitmq:
            condition: service_healthy
    volumes:
      - ./worker2:/app
  notification:
    build: ./notification
    depends_on:
      - rabbitmq
    ports:
      - "8001:8001"
    volumes:
      - ./notification:/app
  client:
      image: python:3.11
      working_dir: /app
      volumes:
        - ./client:/app
      command: python -m http.server 3000
      ports:
        - "3000:3000"